### ISSUE TITLE
yolo format

### ISSUE THREAD

**Issue by Kk875** [enekuie/COCO-json-annotations-to-YOLO-txt-format-converter#1]
hello， How to use the anylabling to annotate the Yolo format dataset? thank you for your answer

**Comment by enekuie** [comment]
honestly I couldn't find any annotations format other than COCO json for anylabling. that's kind of different type of json on top of that (making a json file for each image just like YOLO) and my dataset was in YOLO format too so I had no choice but to wrote this code
